@startmindmap
title Активности группировки DotNetRu

* DotNetRu

** Глобальное сообщество

*** Организация новых сообществ
****_ Лидеры сообществ в новых городах
****_ Активисты для помощи лидерам

*** Новости
****_ <s>Модераторы</s>
****_ Искатели и предлагаторы новостей
****_ Авторы оформители новостей
****_ Распостранители новостей по соц. сетям
****_ Маркетологи

*** Статьи
****_ Авторы оригинальных статей
****_ Авторы переводов
****_ Редакторы, вычитыватели, корректоры

*** Переводы книг
****_ Авторы переводов
****_ Фанаты русского языка
****_ Редакторы, вычитыватели, корректоры

*** Подкасты
****_ <s>Ведущие</s>
****_ Звукорежисёры
****_ Давальщики обратной связи
****_ Распостранители подкастов
****_ Доносчики интересных тем

*** Чат
****_ <s>Модераторы</s>
****_ Активные помогатели ближнему

*** Совместная разработка

**** Audit
*****_ <s>Координатор</s>
*****_ Аудиторы

**** Server
*****_ <s>Координатор</s>
*****_ Разработчики на C#
*****_ Технические писатели

**** DevActivator
*****_ <s>Координатор</s>
*****_ Разработчики на Angular
*****_ UX и UI специалисты
*****_ UI Тестировщики

**** Mobile App
*****_ <s>Координатор</s>
*****_ Разработчики на Xamarin
*****_ UI Тестировщики

*** Стенд
****_ Ведущие
****_ Модераторы круглых столов
****_ Авторы докладов
****_ Составители вопросов к викторине
****_ Авторы квеста
****_ Составитель вопросов к «Что? Где? Когда?»
****_ Ведущие карточных игр
****_ Искатели партнёров
****_ Фотографы

left side

** Локальные встречи

*** Организация регулярных встреч
****_ <s>Лидеры</s>
****_ Искатели партнёров
****_ Искатели мест для проведения встреч
****_ Помощники на площадке
****_ Художники для картинок и инфографики
****_ Авторы анонсов и отчётов о работе сообщества
****_ Аудиторы
****_ Фотографы

*** Лекции от опытных докладчиков
****_ Члены програмного коммитета
****_ Опытные докладчики

*** Подготовка новых докладчиков
****_ Члены програмного коммитета
****_ Новые докладчики

*** Создание видео-коллекций докладов
****_ Видеооператоры
****_ Видеомонтажёры

*** Совместное обучение
****_ Авторы для подготовки мастер-классов

*** Неформальное общение
****_ Неформатные лидеры (бары, завтраки, лыжи, велосипеды)
****_ Помощники, активисты, генераторы идей

*** Освещение специализированных событий в городе
****_ <s>Модераторы</s>
****_ Доносчики интересных событий

*** Поддержка локальных соц. сетей
****_ Составители анонсов
****_ Распространители анонсов
****_ Маркетологи для рекламы сообщества

@endmindmap
